apiVersion: v1
kind: Service
metadata:
  name: task-management-api
  namespace: task-management
  labels:
    app: task-management-api
spec:
  type: LoadBalancer
  selector:
    app: task-management-api
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
